#!/bin/bash
set -euo pipefail
DOVECOT_SNI_CONF="/etc/dovecot/conf.d/99-certbot-mail-sni.conf"
POSTFIX_SNI_MAP="/etc/postfix/vmail_ssl.map"
LIVE_DIR="/etc/letsencrypt/live"
log(){ logger -t "certbot-mail-sni" "$1"; echo "$(date '+%Y-%m-%d %H:%M:%S') - $1"; }
TMP_DOVECOT=$(mktemp)
TMP_POSTFIX=$(mktemp)
trap 'rm -f "$TMP_DOVECOT" "$TMP_POSTFIX"' EXIT
cat > "$TMP_DOVECOT" <<'EOF'

Auto-generated by certbot-mail-sni
DO NOT EDIT
EOF
cat > "$TMP_POSTFIX" <<'EOF'

Auto-generated by certbot-mail-sni
Format: hostname certfile [keyfile]
EOF
find "$LIVE_DIR" -mindepth 1 -maxdepth 1 -type d | while read -r certdir; do
domain=$(basename "$certdir")
[[ "$domain" == mail.* ]] || continue
fullchain="$certdir/fullchain.pem"
privkey="$certdir/privkey.pem"
if [[ -f "$fullchain" && -f "$privkey" ]]; then
if ! openssl x509 -in "$fullchain" -noout >/dev/null 2>&1; then
log "Invalid cert for $domain — skipping"
continue
fi
if ! openssl rsa -in "$privkey" -noout >/dev/null 2>&1; then
log "Invalid or encrypted key for $domain — skipping"
continue
fi
cmod=$(openssl x509 -noout -modulus -in "$fullchain" 2>/dev/null | openssl md5 || true)
kmod=$(openssl rsa -noout -modulus -in "$privkey" 2>/dev/null | openssl md5 || true)
if [[ -n "$cmod" && -n "$kmod" && "$cmod" != "$kmod" ]]; then
log "Cert/key mismatch for $domain — skipping"
continue
fi
log "Enabling SNI for $domain"
cat >> "$TMP_DOVECOT" <<EOD

local_name $domain {
ssl_cert = <$fullchain
ssl_key  = <$privkey
}
EOD
echo "$domain $fullchain $privkey" >> "$TMP_POSTFIX"
else
log "Missing files for $domain — skipping"
fi
done
if ! cmp -s "$TMP_DOVECOT" "$DOVECOT_SNI_CONF" 2>/dev/null; then
install -m 644 "$TMP_DOVECOT" "$DOVECOT_SNI_CONF"
log "Updated Dovecot SNI config"
DOVECOT_CHANGED=1
else
DOVECOT_CHANGED=0
fi
if ! cmp -s "$TMP_POSTFIX" "$POSTFIX_SNI_MAP" 2>/dev/null; then
install -m 644 "$TMP_POSTFIX" "$POSTFIX_SNI_MAP"
postmap "$POSTFIX_SNI_MAP"
chown root:root "$POSTFIX_SNI_MAP" "$POSTFIX_SNI_MAP.db" || true
chmod 644 "$POSTFIX_SNI_MAP" "$POSTFIX_SNI_MAP.db" || true
log "Updated Postfix SNI map"
POSTFIX_CHANGED=1
else
POSTFIX_CHANGED=0
fi
current=$(postconf -h tls_server_sni_maps 2>/dev/null || true)
if [[ "$current" != "$POSTFIX_SNI_MAP" ]]; then
postconf -e "tls_server_sni_maps = hash:$POSTFIX_SNI_MAP"
log "Set tls_server_sni_maps in main.cf"
POSTFIX_CHANGED=1
fi
find "$LIVE_DIR" -mindepth 2 -maxdepth 2 -type f -name privkey.pem | while read -r k; do
if [ -e "$k" ]; then
chown root:postfix "$k" || true
chmod 640 "$k" || true
fi
done
if [ "${DOVECOT_CHANGED:-0}" = "1" ] || [ "${POSTFIX_CHANGED:-0}" = "1" ]; then
if ! find "$LIVE_DIR" -mindepth 2 -maxdepth 2 -type f -name fullchain.pem -exec openssl x509 -in {} -noout \; -print -quit >/dev/null 2>&1; then
log "No valid fullchain found — abort restart"
exit 1
fi
log "Configuration changed → restarting services"
systemctl restart dovecot postfix
log "Restarted postfix and dovecot"
else
log "No changes"
fi
log "SNI update finished"*
